-- Zodra je een raw laag hebt in de database kunnen we dmv queries ons domeinmodel opbouwen
-- Schrijf de queries die we nodig hebben op een domeinmodel op te bouwen
-- Je kunt een table vullen vanuit een query -> zie https://learnsql.com/cookbook/how-to-create-one-table-from-another-table-in-sql/
