-- Zodra we een coherent domeinmodel hebben kunnen we modelleren met onze data
-- Op basis van het domeinmodel kunnen we bijvoorbeeld een view, materialised view of een nieuwe entiteit voor onze visualisatie maken
-- Je kunt een table vullen vanuit een query -> zie https://learnsql.com/cookbook/how-to-create-one-table-from-another-table-in-sql/
